data:
  mode: events
  path: datasets/data/flow/  # datasets/data/UZH-FPV/rotation/
  window: 1000
  window_loss: 10000
experiment: Default
hot_filter:
  enabled: false
  max_px: 100
  max_rate: 0.8
  min_obvs: 5
loader:
  augment:
  - Horizontal
  - Vertical
  - Polarity
  augment_prob:
  - 0
  - 0
  - 0.0
  batch_size: 7
  gpu: 0
  n_epochs: 1
  resolution:
  - 128
  - 128
  rotation_mode: difference
  rotation_type: euler_deg
  seed: 0
loss:
  clip_grad: 100.0
  flow_regul_weight: 0.001
  overwrite_intermediate: false
model:
  activations:
  - relu
  - null
  base_num_channels: 32
  encoding: cnt
  include_init: true
  kernel_size: 3
  mask_output: true
  model_type: conv
  name: FullRotationModel
  norm_input: false
  num_bins: 2
  prev_runid: nervous-ram-566
  round_encoding: false
  transfer_layer: pred
  use_existing: true
optimizer:
  lr: 0.0002
  name: Adam
spiking_neuron: null
vis:
  bars: false
  enabled: false
  px: 400
  store_grads: false
  verbose: true
