data:
  mode: events
  path: datasets/data/UZH-FPV/rotation_train/  # datasets/data/UZH-FPV/flow  
  window: 1000.
  window_loss: 10000
experiment: Default
hot_filter:
  enabled: false
  max_px: 100
  max_rate: 0.8
  min_obvs: 5
loader:
  augment:
  - Horizontal
  - Vertical
  - Polarity
  augment_prob:
  - 0
  - 0
  - 0.0
  batch_size: 8
  gpu: 0
  n_epochs: 1
  resolution:
  - 128
  - 128
  rotation_mode: difference
  rotation_type: euler_deg
  seed: 0
loss:
  clip_grad: 100.0
  flow_regul_weight: 0.001
  overwrite_intermediate: false
model:
  activations:
  - arctanspike
  - arctanspike
  base_num_channels: 32
  encoding: cnt
  include_init: false
  kernel_size: 3
  mask_output: true
  model_type: spiking  # linear, conv or spiking_conv
  name: FullRotationModel
  norm_input: false
  num_bins: 2
  prev_runid: LIFFireNet  # FireNet or E2VID (27-5-bouncy-hog) or EVFlowNet or variations   # previously nervous-ram-566 
  round_encoding: false
  transfer_layer: pred  # for FireNet: head, R1b or pred; for EVFlowNet: multires_unetrec.encoders.0, multires_unetrec.resblocks.0, multires_unetrec.resblocks.1 or multires_unetrec.preds.3; for E2VID: unetrecurrent.head, unetrecurrent.resblocks.0, unetrecurrent.resblocks.1  or unetrecurrent.pred
  use_existing: true
  use_layer_input: false  # set to True to use the input of the layer, useful for bypassing flow network
optimizer:
  lr: 0.0002
  name: Adam
spiking_neuron: #null
    use_spiking: true
    leak: [-4.0, 0.1]
    thresh: [0.8, 0.1]
    learn_leak: True
    learn_thresh: True
    hard_reset: True
vis:
  bars: false
  enabled: false
  px: 400
  store_grads: false
  verbose: true
