experiment: Default

data:
    path: datasets/data/flow/ # datasets/data/UZH-FPV/flow/
    mode: time # events/time
    window: 0.001 # events/time
    window_loss: 10000 # events

model:
    name: EVFlowNet # EVFlowNet/*FireFlowNet/*FireNet/E2VID/RecEVFlowNet, or FullRotationModel
    
    encoding: cnt # voxel/cnt
    round_encoding: False # for voxel encoding
    norm_input: False # normalize input
    num_bins: 2
    base_num_channels: 32
    kernel_size: 3
    activations: [relu, Null] # activations for ff and rec neurons
    mask_output: True

    # new model settings: 
    # model_type: conv 
    # use_existing: true 
    # prev_runid: FireNet  # nervous-ram-566 
    # transfer_layer: pred 
    # use_layer_input: true  # set to True to use the input of the layer, useful for bypassing flow network  
    # include_init: True 

spiking_neuron: 
    use_spiking: False # new
    leak: [-4.0, 0.1]
    thresh: [0.8, 0.1]
    learn_leak: True
    learn_thresh: True
    hard_reset: True
    
loss:
    flow_regul_weight: 0.001
    clip_grad: 100.0 # set to Null to disable
    overwrite_intermediate: False

optimizer:
    name: Adam
    lr: 0.0002

loader:
    # rotation_mode: difference  # absolute / difference / zero-offset  # new
    # rotation_type: euler_deg  # quat / rotvec / matrix / euler / euler_deg  # new
    n_epochs: 100
    batch_size: 1
    resolution: [128, 128] # H x W
    augment: ["Horizontal", "Vertical", "Polarity"]
    augment_prob: [0.5, 0.5, 0.5]  # or [0., 0., 0.] or [0.5, 0.1, 0.]
    gpu: 0

vis:
    verbose: True
    enabled: False
    px: 400
    store_grads: False

hot_filter:
    enabled: False
    max_px: 100
    min_obvs: 5
    max_rate: 0.8
